server {
    listen       80;
    server_name  localhost;

    # Servir archivos estáticos de React (Frontend)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # En entornos de nube como Railway, el frontend se comunica directamente
    # con la URL pública del backend definida en VITE_API_URL, 
    # por lo que no necesitamos definir un proxy pass aquí que bloquee Nginx.

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
