server {
    listen       80;
    server_name  localhost;

    # Servir archivos estáticos de React (Frontend)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # CONFIGURACIÓN DE PROXY (COMENTADA PARA RAILWAY)
    # Solo descomentar si usas Docker Compose local donde el contenedor se llame 'backend'
    
    # location /api/ {
    #     proxy_pass http://backend:5000/api/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }

    # location /static/ {
    #     proxy_pass http://backend:5000/static/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
